# Generated by Django 4.1.4 on 2022-12-27 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_per_user', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('description', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('category', models.CharField(max_length=50)),
                ('id_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.group')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_debt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('id_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.group')),
            ],
        ),
        migrations.CreateModel(
            name='UsersReceiving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.payment')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.user')),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='id_user_paying',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_paying', to='Dashboard.user'),
        ),
        migrations.AddField(
            model_name='payment',
            name='id_users_receiving',
            field=models.ManyToManyField(related_name='users_receiving', through='Dashboard.UsersReceiving', to='Dashboard.user'),
        ),
    ]
